# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/bd_mnist/bd_mnist.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mnist || ORIG_REF_NAME==bd_mnist} -quiet] -quiet

# IP: bd/bd_mnist/ip/bd_mnist_processing_system7_0_0/bd_mnist_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mnist_processing_system7_0_0 || ORIG_REF_NAME==bd_mnist_processing_system7_0_0} -quiet] -quiet

# IP: bd/bd_mnist/ip/bd_mnist_top_mnist_0_0/bd_mnist_top_mnist_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mnist_top_mnist_0_0 || ORIG_REF_NAME==bd_mnist_top_mnist_0_0} -quiet] -quiet

# IP: bd/bd_mnist/ip/bd_mnist_xbar_0/bd_mnist_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mnist_xbar_0 || ORIG_REF_NAME==bd_mnist_xbar_0} -quiet] -quiet

# IP: bd/bd_mnist/ip/bd_mnist_auto_pc_0/bd_mnist_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mnist_auto_pc_0 || ORIG_REF_NAME==bd_mnist_auto_pc_0} -quiet] -quiet

# IP: bd/bd_mnist/ip/bd_mnist_ps7_0_axi_periph_0/bd_mnist_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mnist_ps7_0_axi_periph_0 || ORIG_REF_NAME==bd_mnist_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/bd_mnist/ip/bd_mnist_rst_ps7_0_100M_0/bd_mnist_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mnist_rst_ps7_0_100M_0 || ORIG_REF_NAME==bd_mnist_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/bd_mnist/ip/bd_mnist_xlconcat_0_0/bd_mnist_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mnist_xlconcat_0_0 || ORIG_REF_NAME==bd_mnist_xlconcat_0_0} -quiet] -quiet

# IP: bd/bd_mnist/ip/bd_mnist_axi_dma_0_0/bd_mnist_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mnist_axi_dma_0_0 || ORIG_REF_NAME==bd_mnist_axi_dma_0_0} -quiet] -quiet

# IP: bd/bd_mnist/ip/bd_mnist_xbar_1/bd_mnist_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mnist_xbar_1 || ORIG_REF_NAME==bd_mnist_xbar_1} -quiet] -quiet

# IP: bd/bd_mnist/ip/bd_mnist_auto_us_0/bd_mnist_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mnist_auto_us_0 || ORIG_REF_NAME==bd_mnist_auto_us_0} -quiet] -quiet

# IP: bd/bd_mnist/ip/bd_mnist_auto_pc_1/bd_mnist_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mnist_auto_pc_1 || ORIG_REF_NAME==bd_mnist_auto_pc_1} -quiet] -quiet

# IP: bd/bd_mnist/ip/bd_mnist_axi_mem_intercon_0/bd_mnist_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mnist_axi_mem_intercon_0 || ORIG_REF_NAME==bd_mnist_axi_mem_intercon_0} -quiet] -quiet

# XDC: /media/nisitha/My_Passport/MOODLE/Vivado_projects/cnn_character_recognition/custom_cnn_implementation/custom_nn_implementation/custom_nn_implementation/custom_nn_implementation.gen/sources_1/bd/bd_mnist/bd_mnist_ooc.xdc
