# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/nisitha/My_Passport/MOODLE/Vivado_projects/cnn_character_recognition/custom_cnn_implementation/custom_nn_implementation/custom_nn_implementation/custom_nn_implementation.srcs/sources_1/bd/bd_mnist/ip/bd_mnist_axi_dma_0_0/bd_mnist_axi_dma_0_0.xci
# IP: The module: 'bd_mnist_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/nisitha/My_Passport/MOODLE/Vivado_projects/cnn_character_recognition/custom_cnn_implementation/custom_nn_implementation/custom_nn_implementation/custom_nn_implementation.gen/sources_1/bd/bd_mnist/ip/bd_mnist_axi_dma_0_0/bd_mnist_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_mnist_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /media/nisitha/My_Passport/MOODLE/Vivado_projects/cnn_character_recognition/custom_cnn_implementation/custom_nn_implementation/custom_nn_implementation/custom_nn_implementation.gen/sources_1/bd/bd_mnist/ip/bd_mnist_axi_dma_0_0/bd_mnist_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_mnist_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /media/nisitha/My_Passport/MOODLE/Vivado_projects/cnn_character_recognition/custom_cnn_implementation/custom_nn_implementation/custom_nn_implementation/custom_nn_implementation.gen/sources_1/bd/bd_mnist/ip/bd_mnist_axi_dma_0_0/bd_mnist_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_mnist_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /media/nisitha/My_Passport/MOODLE/Vivado_projects/cnn_character_recognition/custom_cnn_implementation/custom_nn_implementation/custom_nn_implementation/custom_nn_implementation.srcs/sources_1/bd/bd_mnist/ip/bd_mnist_axi_dma_0_0/bd_mnist_axi_dma_0_0.xci
# IP: The module: 'bd_mnist_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/nisitha/My_Passport/MOODLE/Vivado_projects/cnn_character_recognition/custom_cnn_implementation/custom_nn_implementation/custom_nn_implementation/custom_nn_implementation.gen/sources_1/bd/bd_mnist/ip/bd_mnist_axi_dma_0_0/bd_mnist_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_mnist_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /media/nisitha/My_Passport/MOODLE/Vivado_projects/cnn_character_recognition/custom_cnn_implementation/custom_nn_implementation/custom_nn_implementation/custom_nn_implementation.gen/sources_1/bd/bd_mnist/ip/bd_mnist_axi_dma_0_0/bd_mnist_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_mnist_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /media/nisitha/My_Passport/MOODLE/Vivado_projects/cnn_character_recognition/custom_cnn_implementation/custom_nn_implementation/custom_nn_implementation/custom_nn_implementation.gen/sources_1/bd/bd_mnist/ip/bd_mnist_axi_dma_0_0/bd_mnist_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_mnist_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
